# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagios4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagios4
  template:
    metadata:
      labels:
        app: nagios4
    spec:
      containers:
      - name: nagios4
        image: tanzu-harbor.pngd.gob.pe/pcm/nagios:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /user/local/nagios/etc
          name: nagios
      volumes:
      - name: nagios
        persistentVolumeClaim:
          claimName: pvc-nagios

