# pv-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nagios
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: pcmvsanfs06.pngd.gob.pe
    path: /NAGIOS-PNGD

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nagios
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

