# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nagios4
spec:
  selector:
    app: nagios4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30800 # Choose a port number that is not in use and within the valid range
  type: LoadBalancer

